create table if not exists public.password_reset_throttle (
  id bigint generated by default as identity primary key,
  email_hash text not null,
  ip_hash text,
  created_at timestamptz not null default now()
);

create index if not exists password_reset_throttle_email_idx
  on public.password_reset_throttle (email_hash, created_at desc);

create index if not exists password_reset_throttle_ip_idx
  on public.password_reset_throttle (ip_hash, created_at desc)
  where ip_hash is not null;

alter table public.password_reset_throttle enable row level security;
revoke all on public.password_reset_throttle from public, anon, authenticated;